// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace School.Data.Entities;

public class Department
{

    public int DepartmentId { get; set; }

    [Required]
    public string DeptName { get; set; }

    [Required]
    public string DeptDesc { get; set; }

    [Required]
    public string DeptLocation { get; set; }

    public int? DeptManager { get; set; }

    public DateOnly? ManagerHiredate { get; set; }

     
}