// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace School.Data.Entities;

public  class Student
{
 
    public int StudentId { get; set; }
    [Required]
    public string StFname { get; set; }
    [Required]
    public string StLname { get; set; }

    [Required]
    public string StAddress { get; set; }

    public string? Image { get; set; }

    public int? StAge { get; set; }

    [ForeignKey("Department")]
    public int DepartmentId { get; set; }

    public virtual Department Department { get; set; }

 
}